// CRUD operations for Quiz Game

import {
  collection,
  doc,
  getDocs,
  getDoc,
  getDocFromServer,
  addDoc,
  updateDoc,
  deleteDoc,
  query,
  where,
  onSnapshot,
  type Unsubscribe,
} from 'firebase/firestore';
import { db } from '../../lib/firebase';
import type {
  QuizGame,
  GamePlayer,
  CreateGameData,
  GameDifficultyLevel,
} from '../../types/quiz-game';
import type { Flashcard, DifficultyLevel } from '../../types/flashcard';
import type { JLPTQuestion } from '../../types/jlpt-question';
import { COLLECTIONS } from './constants';
import { generateGameCode, shuffleArray } from './utils';
import { generateQuestionsFromFlashcards, generateQuestionsFromJLPT, generateQuestionsForKanjiMode } from './question-generator';

/**
 * Build a card pool that respects the configured difficulty-mix ratios for the chosen game tier.
 *
 * Each game difficulty tier (e.g. "hard") maps to a row in `mixConfig` that describes
 * the desired percentage of super_hard / hard / medium / easy cards.  Cards are grouped
 * into buckets by their individual difficulty flag, then sampled proportionally.
 * Any shortfall in a bucket is filled from cards with no difficulty set (`unset`),
 * and any remaining shortfall (all buckets exhausted) is filled from the full card pool.
 *
 * @param cards          Lesson-scoped flashcards to draw from
 * @param gameDifficulty The selected game difficulty tier
 * @param mixConfig      Full mix table loaded from app settings
 * @param totalRounds    Target pool size (the question generator will slice from this)
 */
function filterByDifficultyMix(
  cards: Flashcard[],
  gameDifficulty: GameDifficultyLevel,
  mixConfig: Record<GameDifficultyLevel, { super_hard: number; hard: number; medium: number; easy: number }>,
  totalRounds: number
): Flashcard[] {
  const row = mixConfig[gameDifficulty];
  const rowTotal = row.super_hard + row.hard + row.medium + row.easy;
  // If all weights are zero the config is degenerate — return fully shuffled pool unchanged
  if (rowTotal === 0) return shuffleArray(cards);

  // Group cards by their individual difficulty level
  const buckets: Record<GameDifficultyLevel, Flashcard[]> = {
    super_hard: [], hard: [], medium: [], easy: [],
  };
  const unset: Flashcard[] = []; // Cards with no difficulty set — used as overflow
  for (const card of cards) {
    const d = card.difficultyLevel as DifficultyLevel;
    if (d && d !== 'unset' && buckets[d as GameDifficultyLevel]) {
      buckets[d as GameDifficultyLevel].push(card);
    } else {
      unset.push(card);
    }
  }

  // Calculate target counts by normalising each weight against the row total
  const levels: GameDifficultyLevel[] = ['super_hard', 'hard', 'medium', 'easy'];
  const selected: Flashcard[] = [];

  for (const diff of levels) {
    const pct = row[diff] / rowTotal;
    const needed = Math.round(pct * totalRounds);
    if (needed <= 0) continue;

    const available = shuffleArray(buckets[diff]);
    const picked = available.slice(0, needed);
    selected.push(...picked);

    // If this bucket is smaller than the target, borrow from the unset pool
    if (picked.length < needed) {
      const deficit = needed - picked.length;
      const supplement = shuffleArray(unset).splice(0, deficit);
      selected.push(...supplement);
    }
  }

  // Final top-up: if buckets + unset still fall short of totalRounds, pad from any unused card
  if (selected.length < totalRounds) {
    const selectedIds = new Set(selected.map(c => c.id));
    const remaining = shuffleArray(cards.filter(c => !selectedIds.has(c.id)));
    selected.push(...remaining.slice(0, totalRounds - selected.length));
  }

  // Re-shuffle so the ordered bucket groups do not produce question patterns
  return shuffleArray(selected);
}

/**
 * Create a new game session in Firestore, routing through one of three question sources:
 *
 *   1. **jlpt** — draws from the JLPT question bank; supports level + category filters.
 *   2. **kanji** — uses lesson flashcards; question = kanji, answer = hiragana reading,
 *                  distractors are phonetically similar hiragana strings.
 *   3. **vocabulary / flashcards** — uses lesson flashcards; question = kanji/vocab,
 *                                    answer = Vietnamese meaning (or vocabulary_meaning).
 *
 * A unique join code is generated by polling Firestore until a collision-free code is found.
 *
 * @param data           Host-submitted game configuration
 * @param hostId         Auth UID of the creating user
 * @param hostName       Display name shown in the lobby
 * @param hostAvatar     Avatar emoji/icon (optional)
 * @param flashcards     All flashcards available to the host (pre-fetched by caller)
 * @param jlptQuestions  JLPT question bank (required when data.source === 'jlpt')
 * @param hostRole       User role string, used for lobby VIP styling
 * @returns              The newly created QuizGame document including its Firestore ID
 */
export async function createGame(
  data: CreateGameData,
  hostId: string,
  hostName: string,
  hostAvatar: string | undefined,
  flashcards: Flashcard[],
  jlptQuestions?: JLPTQuestion[],
  hostRole?: string
): Promise<QuizGame> {
  // Merge caller-supplied overrides with safe defaults so every field is always present
  const settings = {
    minPlayers: 2,
    maxPlayers: 20,
    showLeaderboardEvery: 5,
    specialRoundEvery: 5,
    basePoints: 100,
    streakBonus: 10,
    timeBonus: true,
    ...data.settings,
  };

  let questions;

  if (data.source === 'jlpt' && jlptQuestions) {
    // --- Source 1: JLPT question bank ---
    // Filter down to the levels and categories the host selected
    let filteredQuestions = jlptQuestions;
    if (data.jlptLevels && data.jlptLevels.length > 0) {
      filteredQuestions = filteredQuestions.filter(q => data.jlptLevels!.includes(q.level));
    }
    if (data.jlptCategories && data.jlptCategories.length > 0) {
      filteredQuestions = filteredQuestions.filter(q => data.jlptCategories!.includes(q.category));
    }

    // Require at least 4 questions so that every question can have 3 distinct wrong options
    if (filteredQuestions.length < 4) {
      throw new Error('Cần ít nhất 4 câu hỏi JLPT để tạo game');
    }

    questions = generateQuestionsFromJLPT(
      filteredQuestions,
      data.totalRounds,
      data.timePerQuestion,
      settings.specialRoundEvery
    );
  } else {
    // --- Source 2 & 3: Flashcard-based (vocabulary or kanji mode) ---
    // Narrow the full flashcard pool to only the lessons the host selected
    let lessonCards = flashcards.filter(card => data.lessonIds.includes(card.lessonId));

    // Same minimum as JLPT — need at least 4 cards to form one question with 3 distractors
    if (lessonCards.length < 4) {
      throw new Error('Cần ít nhất 4 thẻ để tạo game');
    }

    // Apply difficulty-mix filtering when the host has configured a difficulty tier.
    // This proportionally selects cards by their individual difficulty flags so the
    // question pool matches the intended challenge profile.
    const gameDifficulty = data.difficultyLevels?.[0];
    if (gameDifficulty && data.difficultyMix) {
      lessonCards = filterByDifficultyMix(lessonCards, gameDifficulty, data.difficultyMix, data.totalRounds);
    }

    if (data.source === 'kanji') {
      // --- Source 2: Kanji mode ---
      // Pass the full flashcard pool (not just lesson cards) so the distractor
      // generator can source phonetically similar readings from a larger candidate set
      questions = generateQuestionsForKanjiMode(
        lessonCards,
        data.totalRounds,
        data.timePerQuestion,
        settings.specialRoundEvery,
        gameDifficulty,
        flashcards,
      );
    } else {
      // --- Source 3: Vocabulary mode (or legacy 'flashcards' alias) ---
      // Pass the full flashcard pool so distractors can be drawn from beyond the selected lessons
      questions = generateQuestionsFromFlashcards(
        lessonCards,
        data.totalRounds,
        data.timePerQuestion,
        settings.specialRoundEvery,
        data.questionContent || 'kanji',
        data.answerContent || 'meaning',
        gameDifficulty,
        flashcards,
      );
    }
  }

  // --- Generate a unique join code ---
  // Codes are random 6-character strings; retry on collision to guarantee uniqueness.
  // Collisions are extremely rare but must be handled to prevent duplicate lobbies.
  let code = generateGameCode();
  let codeExists = true;
  while (codeExists) {
    const existing = await getGameByCode(code);
    if (!existing) {
      codeExists = false;
    } else {
      // Collision detected — generate a new code and try again
      code = generateGameCode();
    }
  }

  const hostPlayer: GamePlayer = {
    id: hostId,
    name: hostName,
    avatar: hostAvatar || '',
    role: hostRole,
    isSpectator: data.hostMode === 'spectate',
    score: 0,
    isHost: true,
    isBlocked: false,
    hasDoublePoints: false,
    hasShield: false,
    hasTimeFreeze: false,
    currentAnswer: null,
    answerTime: null,
    streak: 0,
    correctAnswers: 0,
    joinedAt: new Date().toISOString(),
  };

  const game: Omit<QuizGame, 'id'> = {
    code,
    hostId,
    hostName,
    title: data.title,
    status: 'waiting',
    players: { [hostId]: hostPlayer },
    questions,
    currentRound: 0,
    totalRounds: questions.length,
    timePerQuestion: data.timePerQuestion,
    roundStartTime: null,
    createdAt: new Date().toISOString(),
    settings,
    // Metadata for display in lobby
    source: data.source,
    // Only spread optional fields when they have values — Firestore rejects `undefined`
    ...(data.source === 'jlpt' && data.jlptLevels && data.jlptLevels.length > 0 && { jlptLevels: data.jlptLevels }),
    ...((data.source === 'vocabulary' || data.source === 'kanji' || data.source === 'flashcards') && data.lessonNames && data.lessonNames.length > 0 && { lessonNames: data.lessonNames }),
  };

  const docRef = await addDoc(collection(db, COLLECTIONS.GAMES), game);
  return { id: docRef.id, ...game };
}

export async function getGame(gameId: string): Promise<QuizGame | null> {
  const docRef = doc(db, COLLECTIONS.GAMES, gameId);
  // Always fetch from server to avoid stale cache (critical for power-up writes)
  try {
    const snapshot = await getDocFromServer(docRef);
    if (!snapshot.exists()) return null;
    return { id: snapshot.id, ...snapshot.data() } as QuizGame;
  } catch {
    // Fallback to cache if offline
    const snapshot = await getDoc(docRef);
    if (!snapshot.exists()) return null;
    return { id: snapshot.id, ...snapshot.data() } as QuizGame;
  }
}

export async function getGameByCode(code: string): Promise<QuizGame | null> {
  const q = query(
    collection(db, COLLECTIONS.GAMES),
    where('code', '==', code.toUpperCase())
  );
  const snapshot = await getDocs(q);
  if (snapshot.empty) return null;
  const docSnap = snapshot.docs[0];
  return { id: docSnap.id, ...docSnap.data() } as QuizGame;
}

export async function updateGame(gameId: string, data: Partial<QuizGame>): Promise<void> {
  const docRef = doc(db, COLLECTIONS.GAMES, gameId);
  await updateDoc(docRef, data);
}

/** Field-level update using dot notation (e.g. 'players.abc.score': 100) */
export async function updateGameFields(gameId: string, fields: Record<string, unknown>): Promise<void> {
  const docRef = doc(db, COLLECTIONS.GAMES, gameId);
  await updateDoc(docRef, fields);
}

export async function deleteGame(gameId: string): Promise<void> {
  const docRef = doc(db, COLLECTIONS.GAMES, gameId);
  await deleteDoc(docRef);
}

export function subscribeToGame(gameId: string, callback: (game: QuizGame | null) => void): Unsubscribe {
  return onSnapshot(doc(db, COLLECTIONS.GAMES, gameId), (snapshot) => {
    if (!snapshot.exists()) {
      callback(null);
      return;
    }
    callback({ id: snapshot.id, ...snapshot.data() } as QuizGame);
  });
}
